import {test} from 'node:test';
import assert from 'node:assert/strict';
import app from '../src/index.js';
import {database} from './db.mjs';
import {hashPassword,parseCookies,readJson} from '../src/security.js';
import {collectOverview,collectPending,collectDataQuality,globalSearch} from '../src/data.js';
const env={OPS_DB:database(),SETUP_SECRET:'test-only-setup-key'};
let cookie='',csrf='';
async function call(path,method='GET',body,extra={}){const headers={cookie,'x-csrf-token':csrf,...extra};if(body)headers['content-type']='application/json';const r=await app.fetch(new Request('https://ops.test'+path,{method,headers,body:body?JSON.stringify(body):undefined}),env);return {r,data:await r.json()};}
const user={email:'root@example.test',full_name:'Root Admin',password:'long-test-password-2026'};
test('API integration against SQLite',async t=>{
 await t.test('health without D1',async()=>assert.equal((await app.fetch(new Request('https://ops.test/api/health'),{})).status,200));
 await t.test('bootstrap secret and single initialization',async()=>{assert.equal((await call('/api/setup/bootstrap','POST',user)).r.status,403);assert.equal((await call('/api/setup/bootstrap','POST',user,{'x-setup-secret':env.SETUP_SECRET})).r.status,201);assert.equal((await call('/api/setup/bootstrap','POST',user,{'x-setup-secret':env.SETUP_SECRET})).r.status,409)});
 await t.test('login rejects cross origin',async()=>assert.equal((await call('/api/auth/login','POST',user,{origin:'https://evil.test'})).r.status,403));
 await t.test('login and secure cookie',async()=>{const x=await call('/api/auth/login','POST',user);assert.equal(x.r.status,200);cookie=x.r.headers.get('set-cookie').split(';')[0];csrf=x.data.user.csrf_token;assert.match(x.r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/)});
 await t.test('incidents CSRF, create, resolve and reopen',async()=>{assert.equal((await call('/api/incidents','POST',{title:'Test'},{'x-csrf-token':''})).r.status,403);const x=await call('/api/incidents','POST',{title:'<script>test</script>',severity:'critical',description:'Description'});assert.equal(x.r.status,201);assert.equal((await call('/api/incidents','PATCH',{id:x.data.id,status:'resolved'})).r.status,200);await call('/api/incidents','PATCH',{id:x.data.id,status:'open'});assert.equal(env.OPS_DB.sql.prepare('SELECT resolved_at FROM ops_incidents WHERE id=?').get(x.data.id).resolved_at,null);assert.equal((await call('/api/incidents','PATCH',{id:'absent',status:'open'})).r.status,404)});
 await t.test('own root role protected',async()=>{const me=await call('/api/auth/me');assert.equal((await call('/api/admin/users','PATCH',{id:me.data.user.id,role:'viewer'})).r.status,400)});
 await t.test('forced password change enforced by API; system admin cannot elevate',async()=>{const rootCookie=cookie,rootCsrf=csrf;const account={email:'system@example.test',full_name:'System Admin',role:'system_admin',password:'temporary-password-2026'};assert.equal((await call('/api/admin/users','POST',account)).r.status,201);const x=await call('/api/auth/login','POST',account);cookie=x.r.headers.get('set-cookie').split(';')[0];csrf=x.data.user.csrf_token;assert.equal((await call('/api/overview')).r.status,403);assert.equal((await call('/api/auth/change-password','POST',{current_password:account.password,new_password:'changed-password-2026'})).r.status,200);assert.equal((await call('/api/admin/users','POST',{...user,email:'elevated@example.test',role:'super_admin'})).r.status,403);cookie=rootCookie;csrf=rootCsrf});
 await t.test('missing data is partial, never all clear',async()=>{const x=await call('/api/pending');assert.equal(x.data.partial,true);assert.ok((await collectDataQuality(env,{role:'super_admin'})).skipped>0);assert.equal((await globalSearch(env,{role:'super_admin'},'%%')).length,0)});
 await t.test('report historical permissions',async()=>{env.OPS_DB.sql.prepare('INSERT INTO ops_kpi_snapshots VALUES (?,?,?,?)').run('private','2026',JSON.stringify({generated_by:user.email,overview:{totals:{classes:1}}}),'2026');assert.equal((await call('/api/reports/snapshots/private')).r.status,200);const x=await call('/api/auth/login','POST',{email:'system@example.test',password:'changed-password-2026'});const rootCookie=cookie,rootCsrf=csrf;cookie=x.r.headers.get('set-cookie').split(';')[0];csrf=x.data.user.csrf_token;assert.equal((await call('/api/reports/snapshots/private')).r.status,403);assert.equal((await call('/api/reports/snapshots')).data.items.length,0);cookie=rootCookie;csrf=rootCsrf});
 await t.test('session revoke cannot revoke current',async()=>{const x=await call('/api/auth/sessions');assert.ok(x.data.items.some(s=>s.current));assert.equal((await call('/api/auth/sessions','DELETE',{id:x.data.items.find(s=>s.current).id})).r.status,400)});
 await t.test('query failures return 503, not empty list',async()=>{env.OPS_DB.sql.exec('DROP TABLE ops_incidents');assert.equal((await call('/api/incidents')).r.status,503)});
});
test('malformed cookies ignored',()=>assert.deepEqual(parseCookies(new Request('https://ops.test',{headers:{cookie:'broken=%XY; okay=yes'}})),{okay:'yes'}));
test('JSON byte and type validation',async()=>{await assert.rejects(readJson(new Request('https://ops.test',{method:'POST',body:JSON.stringify({x:'ế'.repeat(30)})}),40),/PAYLOAD_TOO_LARGE/);await assert.rejects(readJson(new Request('https://ops.test',{method:'POST',body:'null'})),/INVALID_JSON/)});
test('visible source totals do not require hidden systems',async()=>{const db=database();db.sql.exec('CREATE TABLE users(id TEXT);INSERT INTO users VALUES ("x")'.replace('"x"',"'x'"));const data=await collectOverview({SLC_DB:db},{role:'viewer',capabilities_json:'["slc.users.view"]'});assert.equal(data.totals.people_and_accounts,1)});
test('scheduled alerts insert, acknowledge, resolve and reopen',async()=>{const local={OPS_DB:database()};const original=globalThis.fetch;let healthy=false;globalThis.fetch=async()=>Response.json({ok:healthy},{status:healthy?200:503});const run=async()=>{let promise;app.scheduled({},local,{waitUntil(p){promise=p}});await promise;};try{await run();const first=local.OPS_DB.sql.prepare('SELECT * FROM ops_alerts LIMIT 1').get();assert.ok(first);local.OPS_DB.sql.prepare("UPDATE ops_alerts SET status='acknowledged' WHERE id=?").run(first.id);await run();assert.equal(local.OPS_DB.sql.prepare('SELECT status FROM ops_alerts WHERE id=?').get(first.id).status,'acknowledged');healthy=true;await run();assert.equal(local.OPS_DB.sql.prepare('SELECT status FROM ops_alerts WHERE id=?').get(first.id).status,'resolved');healthy=false;await run();assert.equal(local.OPS_DB.sql.prepare('SELECT status FROM ops_alerts WHERE id=?').get(first.id).status,'open');}finally{globalThis.fetch=original;}});
